databases:
  - name: Scared-off Championship
    databaseName: scared_off_championship
    user: scared_off_championship_user
    region: singapore

services:
  - type: web
    name: scared-off-championship-app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Scared-off Championship
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false